return {}
-- return {
-- 	"akinsho/bufferline.nvim",
-- 	dependencies = { "nvim-tree/nvim-web-devicons" },
-- 	opts = {
-- 		options = {
-- 			separator_style = "thin",
-- 			modified_icon = "~",
-- 			close_icon = "",
-- 		},
-- 	},
-- 	config = function()
-- 		require("bufferline").setup({
-- 			options = {
-- 				offsets = {
-- 					{
-- 						filetype = "neo-tree",
-- 						text = "File Explorer",
-- 						highlight = "Directory",
-- 						separator = true, -- use a "true" to enable the default, or set your own character
-- 					},
-- 				},
-- 			},
-- 		})
-- 	end,
-- }
