### Color settings
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -as terminal-features ",xterm-255color:sync"
set -g focus-events on

### General
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix
set -g mouse on # Mouse support
set -s escape-time 0
set -g history-limit 50000
set -g base-index 1 # Start counting at 1 for panes and windows
setw -g pane-base-index 1
set -g renumber-windows on # Renumbering after swapping windows

### Keybindings

# Splitting
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Swap windows
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# Navigating panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
